# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data1/lijinwang/ctest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data1/lijinwang/ctest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data1/lijinwang/ctest/CMakeFiles /data1/lijinwang/ctest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data1/lijinwang/ctest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myapp

# Build rule for target.
myapp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myapp
.PHONY : myapp

# fast build rule for target.
myapp/fast:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/build
.PHONY : myapp/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f third_party/prometheus-cpp/CMakeFiles/gmock_main.dir/build.make third_party/prometheus-cpp/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) -f third_party/prometheus-cpp/core/CMakeFiles/core.dir/build.make third_party/prometheus-cpp/core/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named prometheus_core_test

# Build rule for target.
prometheus_core_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prometheus_core_test
.PHONY : prometheus_core_test

# fast build rule for target.
prometheus_core_test/fast:
	$(MAKE) -f third_party/prometheus-cpp/core/tests/CMakeFiles/prometheus_core_test.dir/build.make third_party/prometheus-cpp/core/tests/CMakeFiles/prometheus_core_test.dir/build
.PHONY : prometheus_core_test/fast

#=============================================================================
# Target rules for targets named prometheus_util_test

# Build rule for target.
prometheus_util_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prometheus_util_test
.PHONY : prometheus_util_test

# fast build rule for target.
prometheus_util_test/fast:
	$(MAKE) -f third_party/prometheus-cpp/util/tests/unit/CMakeFiles/prometheus_util_test.dir/build.make third_party/prometheus-cpp/util/tests/unit/CMakeFiles/prometheus_util_test.dir/build
.PHONY : prometheus_util_test/fast

#=============================================================================
# Target rules for targets named pull

# Build rule for target.
pull: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pull
.PHONY : pull

# fast build rule for target.
pull/fast:
	$(MAKE) -f third_party/prometheus-cpp/pull/CMakeFiles/pull.dir/build.make third_party/prometheus-cpp/pull/CMakeFiles/pull.dir/build
.PHONY : pull/fast

#=============================================================================
# Target rules for targets named civetweb

# Build rule for target.
civetweb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 civetweb
.PHONY : civetweb

# fast build rule for target.
civetweb/fast:
	$(MAKE) -f third_party/prometheus-cpp/pull/CMakeFiles/civetweb.dir/build.make third_party/prometheus-cpp/pull/CMakeFiles/civetweb.dir/build
.PHONY : civetweb/fast

#=============================================================================
# Target rules for targets named sample_server_auth

# Build rule for target.
sample_server_auth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample_server_auth
.PHONY : sample_server_auth

# fast build rule for target.
sample_server_auth/fast:
	$(MAKE) -f third_party/prometheus-cpp/pull/tests/integration/CMakeFiles/sample_server_auth.dir/build.make third_party/prometheus-cpp/pull/tests/integration/CMakeFiles/sample_server_auth.dir/build
.PHONY : sample_server_auth/fast

#=============================================================================
# Target rules for targets named sample_server_multi

# Build rule for target.
sample_server_multi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample_server_multi
.PHONY : sample_server_multi

# fast build rule for target.
sample_server_multi/fast:
	$(MAKE) -f third_party/prometheus-cpp/pull/tests/integration/CMakeFiles/sample_server_multi.dir/build.make third_party/prometheus-cpp/pull/tests/integration/CMakeFiles/sample_server_multi.dir/build
.PHONY : sample_server_multi/fast

#=============================================================================
# Target rules for targets named prometheus_pull_integration_test

# Build rule for target.
prometheus_pull_integration_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prometheus_pull_integration_test
.PHONY : prometheus_pull_integration_test

# fast build rule for target.
prometheus_pull_integration_test/fast:
	$(MAKE) -f third_party/prometheus-cpp/pull/tests/integration/CMakeFiles/prometheus_pull_integration_test.dir/build.make third_party/prometheus-cpp/pull/tests/integration/CMakeFiles/prometheus_pull_integration_test.dir/build
.PHONY : prometheus_pull_integration_test/fast

#=============================================================================
# Target rules for targets named sample_server

# Build rule for target.
sample_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample_server
.PHONY : sample_server

# fast build rule for target.
sample_server/fast:
	$(MAKE) -f third_party/prometheus-cpp/pull/tests/integration/CMakeFiles/sample_server.dir/build.make third_party/prometheus-cpp/pull/tests/integration/CMakeFiles/sample_server.dir/build
.PHONY : sample_server/fast

#=============================================================================
# Target rules for targets named prometheus_pull_test

# Build rule for target.
prometheus_pull_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prometheus_pull_test
.PHONY : prometheus_pull_test

# fast build rule for target.
prometheus_pull_test/fast:
	$(MAKE) -f third_party/prometheus-cpp/pull/tests/unit/CMakeFiles/prometheus_pull_test.dir/build.make third_party/prometheus-cpp/pull/tests/unit/CMakeFiles/prometheus_pull_test.dir/build
.PHONY : prometheus_pull_test/fast

#=============================================================================
# Target rules for targets named push

# Build rule for target.
push: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 push
.PHONY : push

# fast build rule for target.
push/fast:
	$(MAKE) -f third_party/prometheus-cpp/push/CMakeFiles/push.dir/build.make third_party/prometheus-cpp/push/CMakeFiles/push.dir/build
.PHONY : push/fast

#=============================================================================
# Target rules for targets named sample_client

# Build rule for target.
sample_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample_client
.PHONY : sample_client

# fast build rule for target.
sample_client/fast:
	$(MAKE) -f third_party/prometheus-cpp/push/tests/integration/CMakeFiles/sample_client.dir/build.make third_party/prometheus-cpp/push/tests/integration/CMakeFiles/sample_client.dir/build
.PHONY : sample_client/fast

#=============================================================================
# Target rules for targets named prometheus_push_internal_test

# Build rule for target.
prometheus_push_internal_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prometheus_push_internal_test
.PHONY : prometheus_push_internal_test

# fast build rule for target.
prometheus_push_internal_test/fast:
	$(MAKE) -f third_party/prometheus-cpp/push/tests/internal/CMakeFiles/prometheus_push_internal_test.dir/build.make third_party/prometheus-cpp/push/tests/internal/CMakeFiles/prometheus_push_internal_test.dir/build
.PHONY : prometheus_push_internal_test/fast

audio_afade.o: audio_afade.cc.o

.PHONY : audio_afade.o

# target to build an object file
audio_afade.cc.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/audio_afade.cc.o
.PHONY : audio_afade.cc.o

audio_afade.i: audio_afade.cc.i

.PHONY : audio_afade.i

# target to preprocess a source file
audio_afade.cc.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/audio_afade.cc.i
.PHONY : audio_afade.cc.i

audio_afade.s: audio_afade.cc.s

.PHONY : audio_afade.s

# target to generate assembly for a file
audio_afade.cc.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/audio_afade.cc.s
.PHONY : audio_afade.cc.s

av_metrics.o: av_metrics.cc.o

.PHONY : av_metrics.o

# target to build an object file
av_metrics.cc.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/av_metrics.cc.o
.PHONY : av_metrics.cc.o

av_metrics.i: av_metrics.cc.i

.PHONY : av_metrics.i

# target to preprocess a source file
av_metrics.cc.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/av_metrics.cc.i
.PHONY : av_metrics.cc.i

av_metrics.s: av_metrics.cc.s

.PHONY : av_metrics.s

# target to generate assembly for a file
av_metrics.cc.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/av_metrics.cc.s
.PHONY : av_metrics.cc.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... myapp"
	@echo "... gmock_main"
	@echo "... core"
	@echo "... prometheus_core_test"
	@echo "... prometheus_util_test"
	@echo "... pull"
	@echo "... civetweb"
	@echo "... sample_server_auth"
	@echo "... sample_server_multi"
	@echo "... prometheus_pull_integration_test"
	@echo "... sample_server"
	@echo "... prometheus_pull_test"
	@echo "... push"
	@echo "... sample_client"
	@echo "... prometheus_push_internal_test"
	@echo "... audio_afade.o"
	@echo "... audio_afade.i"
	@echo "... audio_afade.s"
	@echo "... av_metrics.o"
	@echo "... av_metrics.i"
	@echo "... av_metrics.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

